### ISSUE TITLE
Support for PostgreSQL `OVERLAPS` date/time operator

### ISSUE THREAD

**Issue by cbortz** [GeorgeKaraszi/ActiveRecordExtended#19]
Neat project you've got here! I found it through [a post on Reddit](https://www.reddit.com/r/ruby/comments/b4p7s0/activerecordextended_v10_add_that_missing_pg/).

I'm curious if there's been any consideration to add support for the PostgreSQL `OVERLAPS` operator, as outlined in [Date/Time Functions and Operators](https://www.postgresql.org/docs/11/functions-datetime.html)? If interested, I'd be happy to discuss and potentially open a pull request.

Cheers!

**Comment by GeorgeKaraszi** [comment]
Hey that's not a bad idea. I do have a few idea's I wanna get off my plate before getting into this feature. But one thing that could help is if you could come up with an API proposal for some of these important features you're interested in.
