### ISSUE TITLE
Is there a ".all" method collision?

### ISSUE THREAD

**Issue by StanBright** [GeorgeKaraszi/ActiveRecordExtended#20]
I has a quick look over ARE, and it looks pretty good. To be honest,  I'm eager to give it a try. 

My only concern, currently, is reimplementing/overwriting the regular AR `.all` method. What's the reasoning behind it?

**Comment by GeorgeKaraszi** [comment]
There's no overwriting `.all`. If you are referring to `where.all` calling just `where` alone with no arguments, creates a new instance called `WhereChain`. It's how you access to `where.not`.. Doing something like `where.all` without this gem will raise a `NoMethodError` exception.
