### ISSUE TITLE
Upgrade pg gem dependency

### ISSUE THREAD

**Issue by galetahub** [GeorgeKaraszi/ActiveRecordExtended#21]
Hi,
Many thanks for your work!
I have one question:
Is it possible to upgrade pg gem dependency to the latest version 1.1.4?

**Comment by GeorgeKaraszi** [comment]
Yea thats not a problem, I can run a few tests and prepare a new minor release soon. There was an issue (a year ago?) where the PG gem and Rails wasn't "acting" correctly. I can't remember the specific details on what the issue was (again a year ago) but it might have been resolved.
