### ISSUE TITLE
Typo in ReadMe file

### ISSUE THREAD

**Issue by ccartano** [GeorgeKaraszi/ActiveRecordExtended#32]
In the readme file it shows:
```ruby
user_1 = Person.where(id: 1)
user_2 = Person.where(id: 2)
users  = Person.where(id: 1..3)

Person.union(user_1, user_2, users) #=> [#<Person id: 1, ..>, #<Person id: 2,..>, #<Person id: 3,..>]

# You can also chain union's
Person.union(user_1).union(user_2).union(users)
```

But when using the union method in rails, it will throw an error `NoMethodError: undefined method 'union' for #<Class:0x00007fcf10868468>`

To get this to work, with the example from the readme, I would need to call it as `Person.all.union(user_1, user_2, users)` 

The readme should be updated to reflect this.

**Comment by GeorgeKaraszi** [comment]
Hey sorry for the late response, I've been on vacation.

Can you provide more details? I personally haven't ran across this issue. Especially since `.union` is delegated through `.all` (as are 99% of all AR query methods)

**Comment by ccartano** [comment]
We are specifically using:
Postgres v11.2 
ActiveRecordExtended v1.3.1

In my example I was doing something like:
```ruby
User.union(active_users, admin_users)
```
where `active_users` and `admin_users` are scopes that do where queries.

Ive also tried assigning them to variables just in case, but I still get the no method error.
Im not sure what else I can provide to point you in the right direction. But let me know!

**Comment by GeorgeKaraszi** [comment]
Is it that you are missing `User` class for each scope? 

I.E: `User.union(User.active_users, User.admin_users)`

The several project that share very similar spec's that you have listed, I haven't had a problem.

Here something I just put together and ran
```ruby

User < ActiveRecord::Base
   scope :sale_users,    -> { where(sale_user: true) }
   scope :admin_users, -> { where(admin: true) }
   scope :union_them,  -> { union(sale_users, admin_users) }   
end

```

In rails console I do:

`User.union(User.sale_users, User.admin_users)` or `User.union_them`

sql output:
```sql
SELECT "users".*
  FROM (
  (
  (
    SELECT "users".*
    FROM "users"
    WHERE "users"."sale_user" = 't'
  ) UNION
  (
    SELECT "users".*
    FROM "users"
    WHERE "users"."admin" = 't'
  )
)
) users
```

**Comment by ccartano** [comment]
This issue is totally on our end. Looks like we are using a gem called `deep_cloneable v2.4.0` which was causing a conflict issue. Bumping the gem to `v3.0.0` allows the `.union` to work without the `.all`

**Comment by Tuxii** [comment]
Hi there,

It seems the issue reappeared in the latest version. I can't call `union` on the class, but only on a relation (using `all` or something else).
