### ISSUE TITLE
undefined method `with` for Model

### ISSUE THREAD

**Issue by lalitlogical** [GeorgeKaraszi/ActiveRecordExtended#42]
I have followed the [installation](https://github.com/GeorgeKaraszi/ActiveRecordExtended#installation) step as below.

Add this line to your application's Gemfile:

`gem 'active_record_extended'`
And then execute:

`$ bundle`

Why I'm still getting the below issue?

```
irb(main):002:0> Developer.with
Traceback (most recent call last):
        1: from (irb):2
NoMethodError (undefined method `with' for Developer (call 'Developer.connection' to establish a connection):Class)
irb(main):003:0>
```

Rails version: gem 'rails', '~> 5.1.4'
Ruby version: ruby-2.5.0

Should I have to require any module manually in Models?

**Comment by lalitlogical** [comment]
Finally, I figure out the issue. We have to require the below into application.rb 

require "active_record_extended"

But it should be mentioned in ReadMe for better clarity.

**Comment by leoplct** [comment]
Same problem. It's better to mentioned in the Readme.

**Comment by GeorgeKaraszi** [comment]
odd, I've worked on many projects with this gem. Not once have I ever had to explicitly require it.
