### ISSUE TITLE
use this with simple_form_for

### ISSUE THREAD

**Issue by Faisal-nfl** [GeorgeKaraszi/ActiveRecordExtended#45]
Can use this with simple form for like

`= f.input :log_cardholderName_jcont, label:false, required:false, placeholder:'Log', type: 'string'`

where cardholderName is key in jsonb of log column
OR 

`= f.input :log_jcont, label:false, required:false, placeholder:'Log', type: 'string'`

**Comment by GeorgeKaraszi** [comment]
I'm sorry, not sure I fully understand your question.
