### ISSUE TITLE
need support for rails 6.1

### ISSUE THREAD

**Issue by jicheng1014** [GeorgeKaraszi/ActiveRecordExtended#49]
i saw the pr https://github.com/GeorgeKaraszi/ActiveRecordExtended/pull/47 fixed the problem, but ci fail.

**Comment by GeorgeKaraszi** [comment]
Planning for a release here soon to help address rails 6.1 and other outstanding issue's in the very near future.

**Comment by GeorgeKaraszi** [comment]
Released v2.0 with Rails 6.1 support
