### ISSUE TITLE
Arel::Nodes::Contains Warnings with Rails 6.1

### ISSUE THREAD

**Issue by fny** [GeorgeKaraszi/ActiveRecordExtended#52]
Just upgrade to 6.1 and got these two warnings:

    /Users/fny/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/active_record_extended-2.0.0/lib/active_record_extended/arel/nodes.rb:14: warning: already initialized constant Arel::Nodes::Contains
    /Users/fny/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.0/lib/arel/nodes/infix_operation.rb:50: warning: previous definition of Contains was here

It seems like Contains should be dropped if Rails.version > '6.1.0'

**Comment by GeorgeKaraszi** [comment]
Okay, I'll address it in a patch soon.

**Comment by GeorgeKaraszi** [comment]
Fix is currently sitting on `master`. No ETA for a new release atm.

**Comment by DanAndreasson** [comment]
@GeorgeKaraszi any chance we could see a `2.0.1` any time soon?

**Comment by maximeg** [comment]
Interested too!
