### ISSUE TITLE
Undefined method 'union' on test environment

### ISSUE THREAD

**Issue by drselump14** [GeorgeKaraszi/ActiveRecordExtended#53]
```
gem version: v2.0.0
```

Using `Post.union` only works on the development environment but raises an error in the test environment.
`Post.all.union` works in both environments.
Is it the intended behavior? because I can't found the documentation about it in Readme.

Any help would be appreciated. Thanks~

**Comment by PedroAugustoRamalhoDuarte** [comment]
I had this same error in rails console, i follow this instructions and it works: https://github.com/GeorgeKaraszi/ActiveRecordExtended/issues/50#issuecomment-782677937

**Comment by GeorgeKaraszi** [comment]
closing this issue since recent changes might have resolved this concern. Open a new issue if this persists.
