### ISSUE TITLE
Question: Can't Figure Out Manager Tree

### ISSUE THREAD

**Issue by Merovex** [GeorgeKaraszi/ActiveRecordExtended#54]
Forgive me for being a bit out of my element here. I'm coming back to Rails after a decade and haven't had to handle complex SQL in longer than that.

I'm trying to work the Manager's Tree sort of problem using the block of code below. This specific example should return 11 records, and the UUID is the root level manager. I have 102 Group records in this database, which are all returned by this query. So, my query seems to be the equivalent of `Group.all`.

```
group = Group.where(id: '7918c477-8843-471a-bfcd-e47982fed0c6')
recursive = Group.joins('JOIN gtree ON gtree.id = groups.parent_id')
Group.with.recursive(gtree: Group.union_all(group, recursive).to_union_sql)
```

A dump of the SQL:

```
WITH RECURSIVE "gtree" AS ((
    (SELECT "groups".* 
     FROM "groups"
     WHERE "groups"."id" = '7918c477-8843-471a-bfcd-e47982fed0c6')
UNION ALL
    (SELECT "groups".*
    FROM "groups"
    JOIN gtree ON gtree.id = groups.parent_id)
))

SELECT "groups".* FROM "groups"
```

When I look at a [SQL exemplar](https://towardsdatascience.com/recursive-sql-queries-with-postgresql-87e2a453f1b) (Real World Examples section for getting the manager tree), they look virtually identical. Which leads me to wonder what I'm doing wrong.

Suggestions?

Edit: At the parent level, parent_id is null. Any group not belonging to a network has parent_id null. But, when I add not null, there's no change.

```
 group = Group.where(id: '7918c477-8843-471a-bfcd-e47982fed0c6').where.not(parent_id: nil)
 recursive = Group.joins('JOIN gtree ON gtree.id = groups.parent_id')
Group.with.recursive(gtree: Group.union_all(group, recursive).to_union_sql)
````

```
WITH RECURSIVE "gtree" AS ((
   (SELECT "groups".* 
    FROM "groups"
    WHERE "groups"."id" = '7918c477-8843-471a-bfcd-e47982fed0c6' 
        AND "groups"."parent_id" IS NOT NULL)
UNION ALL
    (SELECT "groups".* FROM "groups" JOIN gtree ON gtree.id = groups.parent_id)
))

SELECT "groups".* FROM "groups"
```

**Comment by GeorgeKaraszi** [comment]
this `SELECT "groups".* FROM "groups"` needs to turn into this `SELECT "gtree".* FROM "gtree"`

**Comment by Merovex** [comment]
Okay. I'm looking at that now, though after a full day I'm a bit foggy. I think that query is being built in the 
statement ```Group.union_all(group, recursive).to_union_sql```

**Comment by Merovex** [comment]
I've spent a couple hours trying to find how to get the following statement:

```
group = Group.where(id: root_id)
recursive = Group.joins('JOIN gtree ON gtree.id = groups.parent_id')
Group.with.recursive(gtree: Group.union_all(group, recursive).to_union_sql)
```

To create `SELECT "gtree".* FROM "gtree"` as the final query instead of `SELECT "groups".* FROM "groups"`

The closest I've gotten was:

```
group = Group.where(id: root_id)
recursive = Group.joins('JOIN gtree ON gtree.id = groups.parent_id')
Group.select('gtree.*').with.recursive(gtree: Group.union_all(group, recursive).to_union_sql)
```

which got me to `SELECT "gtree".* FROM "groups"`

I've read through your code and your tests. I don't see anywhere it's possible in ARExtended.

**Comment by GeorgeKaraszi** [comment]
You have 2 options.

Either:

` Group.with.recursive(gtree: ...).select("*").from("gtree")`

or

`Group.with.recursive(gtree: ...).joins("INNER JOIN gtree ON gtree.id = groups.id")`

**Comment by Merovex** [comment]
Wait...I have choices?! How dare you give me options. :-)

Here's what I have which appears to be working as advertized. 

```
base = Group.where(id: root_id)
recursive = Group.joins('JOIN gtree ON gtree.id = groups.parent_id')
Group.with.recursive(
   gtree: Group.union_all(base, recursive).to_union_sql
).select("*").from("gtree")
```

Thank you for your patience. And, for letting me mind-dump in the comments of this question so others might benefit. I am very glad I was able to get ActiveRecord Extended to work. Keep up the good work.

**Comment by Merovex** [comment]
For what it's worth, the original query tracked around 36-42ms, this query was 0.9ms. That's a 4-5x improvement
