### ISSUE TITLE
SELECT FROM THE CTE table name

### ISSUE THREAD

**Issue by leoplct** [GeorgeKaraszi/ActiveRecordExtended#59]
I have to create a query like this below
```
WITH cte AS (
  SELECT 
       "items"."title", 
        "items"."parent_code", 
       "items"."spend", (ROW_NUMBER() OVER number_window) AS "rank" 
    FROM "items" 
    WHERE "items"."profile_id" = 34 
   WINDOW number_window AS (PARTITION BY profile_id ORDER BY spend DESC)
 )


SELECT title, parent_code
FROM   cte
WHERE  rank = 1;
```

I can write the query inside the WITH

`parents = Item.define_window(:number_window)
                           .partition_by(:profile_id, order_by: {spend: :desc})
                           .select(:title, :parent_code, :spend)
                          .select_window(:row_number, over: :number_window, as: :rank)
                         .where(profile_id: profile_ids)`

but how to write the rest ?

```
SELECT title, parent_code
FROM   cte
WHERE  rank = 1;
```

If I try with

`Item.with(parents: parents).where(rank: 1)`

I get 

`SELECT * FROM items WHERE items.rank=1`

instead I want to SELECT FROM the parents table (the CTE table)

**Comment by GeorgeKaraszi** [comment]
That is expected behavior. You need to either use it in your `form` clause, join it, or use in it a subquery.

```
comments = Comment.select(:id, :user_id, :message)
User
  .with(comments_cte: comments)
  .joins("INNER JOIN comments_cte ON comments_cte.user_id = users.id")
  .where(comments_cte: { message: "Hello World" }) 
```
