### ISSUE TITLE
`ar_outer_joins` dependency?

### ISSUE THREAD

**Issue by spovich** [GeorgeKaraszi/ActiveRecordExtended#70]
This library looks great, but I'm puzzled by the inclusion of the `ar_outer_joins` library as a dependency considering it hasn't had a release in 8 years.   Looks like it is only used by `either_join` and `either_order`. 

Is anyone else concerned by that, or not?

**Comment by GeorgeKaraszi** [comment]
I don't think it's an issue. If anything it's a testament to how well the library was created that it survived the test of time, despite all the Rail's changes over the years.
