### ISSUE TITLE
Merging union queries leads to conditionless queries

### ISSUE THREAD

**Issue by medranocalvo** [GeorgeKaraszi/ActiveRecordExtended#73]
Unions are not preserved when merging.  Please see testcase below.

To give more context: this can have critical consequences.  For example, when using unions in scopes which end up in CanCanCan rules it leads to all records being accessible, irrespective of the scope, as CanCanCan merges them when calculating the accessible records.

I see that there's code in relation_patch.rb but it seems that it's no longer to working.  For example, I cannot find the method `normal_values` in Rails (anymore?); instead there is a constant `NORMAL_VALUES`.  As a quick-n-dirty try I added `:unionize`  to this constant, but leads to an error due to the method `unionize!` not existing.

```diff
diff --git i/spec/query_methods/unionize_spec.rb w/spec/query_methods/unionize_spec.rb
index bbd77fb..ff0879e 100644
--- i/spec/query_methods/unionize_spec.rb
+++ w/spec/query_methods/unionize_spec.rb
@@ -49,6 +49,14 @@ RSpec.describe "Active Record Union Methods" do
       query        = User.union(User.select(:id), User.select(:id))
       expect(query.pluck(:id)).to have_attributes(size: expected_ids.size).and(match_array(expected_ids))
     end
+
+    context "when merging in query" do
+      it "will maintain the union table when merging into existing AR queries" do
+        other = User.union(User.where(id: user_one.id), User.joins(:profile_l).where.not(id: user_one.id))
+        query = User.merge(other)
+        expect(query).to match_array(other.to_a)
+      end
+    end
   end

   describe ".union.all" do
```

**Comment by GeorgeKaraszi** [comment]
Hey @medranocalvo I haven't forgotten your request (been busy). But I do have a fix in place and am currently testing: https://github.com/GeorgeKaraszi/ActiveRecordExtended/pull/75

**Comment by medranocalvo** [comment]
We're all busy.

Thank you very much for working on this.  I'll comment on the PR.

**Comment by GeorgeKaraszi** [comment]
Closing this as the issue seems to have been resolved.
