### ISSUE TITLE
contains visitor breaks rails native Arel::Nodes::Contains for irregular table names

### ISSUE THREAD

**Issue by davidgoldelocks** [GeorgeKaraszi/ActiveRecordExtended#74]
Rails added `Arel::Nodes::Contains` back in version 6.1 (see https://github.com/rails/rails/commit/3a8eee9117637131a6caf77df3bfca5fcc0d6cd1)

The visitor in this library breaks the native implementation when the table name does not exactly map to the model class:
https://github.com/GeorgeKaraszi/ActiveRecordExtended/blob/7bbce1cea37ba25f49da31b4167d3d33d4354466/lib/active_record_extended/arel/visitors/postgresql_decorator.rb#L16-L19

Specifically the `constantize` fails with `NameError: uninitialized constant <Thing>`.

You run into this if you namespace your models (`Models::Thing`) or you manually set `self.table_name=`

(and you are using the native contains node in some fashion e.g `arel_table[column_name].contains(...)`)

This library avoids the issue by making a `ContainsHStore` directly in the where_chain builder: https://github.com/GeorgeKaraszi/ActiveRecordExtended/blob/8c9d1a3e72aabf1a4f1fbeeb93a6e0f170fd0c3e/lib/active_record_extended/query_methods/where_chain.rb#L53-L54

There seem to be two potential solutions. The current implementation of `visit_Arel_Nodes_Contains` has to proxy between the various containment subtypes, so:

a) remove this visitor all-together by moving the proxy logic earlier (ala where_chain) and not using `Arel::Nodes::Contains` at all in this library

b) rewrite the column type lookup logic to handle irregular table names gracefully

semi-related to #25 #26

**Comment by GeorgeKaraszi** [comment]
Since AR 6.1 is doing nearly everything I had originally set out to do for contains, years after. I'm leaning towards just removing these methods altogether (if AR >= 6.1) https://github.com/GeorgeKaraszi/ActiveRecordExtended/pull/76

**Comment by GeorgeKaraszi** [comment]
Closing this since a new release was just pushed. If this problem still occurs or something else arises, please feel free to open another issue and perhaps a PR too 👍 .

**Comment by davidgoldelocks** [comment]
thanks!
